### PR TITLE
#112 Fix the MORE link

### PR DESCRIPTION
**Pull request by pbenety**
Fix the MORE link for #112

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#209](https://github.com/yegor256/0pdd/issues/209) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#209](https://github.com/yegor256/0pdd/issues/209); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#209](https://github.com/yegor256/0pdd/issues/209) is now out of scope

**Comment by 0crat** [comment]
The job [#209](https://github.com/yegor256/0pdd/issues/209) is now out of scope

**Pull request merged**
