### PR TITLE
Retrieves Organization Invitations from GitHub. Closes #143

### LINKED ISSUE #143: automatically accept GitHub invitations to organizations
At the moment we only accept repository invitations. Let's accept ones into organizations.

### PR DESCRIPTION
**Pull request by SilasReinagel**
Closes #134. Discovered how to retrieve list of Github Organization Invites. 

- Created a puzzle for figuring out how to accept Organization Invites.
- Updated Repository invitation message to disambiguate from other invitation acceptances

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@SilasReinagel this pull request is too small, just 7 lines changed (less than 10), there will be no formal code review; in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by SilasReinagel** [comment]
@yegor256 I removed the space Rultor complained about. Try merging again.

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0pdd** [comment]
@SilasReinagel the only puzzle [#199](https://github.com/yegor256/0pdd/issues/199) is solved here.

**Pull request merged**
