### PR TITLE
[#339] 0pdd Jira support

### PR DESCRIPTION
**Pull request by Doldrums**
## Pull Request resolves issue [#339] - 0pdd support for Jira, and dedicated to Jira integration to 0pdd source code
In general, here is an extension of the logic of version control systems, by adding
    ✅ Jira client class implementation
    ✅ Jira repository class implementation
    ✅ Jira-ruby gem dependencies
    ✅ Jira tickets body template implementation
## Environment 
JIRA API Gem `jira-ruby`. This gem provides access to the Atlassian JIRA REST API.
https://github.com/sumoheavy/jira-ruby
## Test coverage 
next PR.

### CODE REVIEW

**Comment by Doldrums** [comment]
@yegor256 try again pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by Doldrums** [comment]
@yegor256 fixed merge conflicts

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
