### PR TITLE
#267 bump ruby version

### PR DESCRIPTION
**Pull request by lastk**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@lastk[/z](https://www.0crat.com/u/lastk) this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@lastk it seems to be not mergeable?

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#268` is not assigned, can't get performer

**Pull request closed without merging**
