### PR TITLE
#125 add autostash option and git ignore for intellij

### PR DESCRIPTION
**Pull request by mesut**
#125 solved

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@mesut[/z](https://www.0crat.com/u/mesut) this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#226` is not assigned, can't get performer

**Comment by mesut** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/0pdd/issues/226#issuecomment-403527761))

@mesut Job [#226](https://github.com/yegor256/0pdd/issues/226) is not in scope, can't put it on hold

**Pull request merged**
