### PR TITLE
[312] refactor codebase to be github independent

### PR DESCRIPTION
**Pull request by mbao01**
refactored code to allow any VCS to be added easily
refactored code to allow any issue management software to be added easily

* [x] Refactoring ♻️
* [x] New tests added to cover changes in this PR
* [x] All tests passing
* [x] Lint passing

### CODE REVIEW

**Comment by Doldrums** [comment]
@yegor256 review please

**Comment by mbao01** [comment]
Please review @yegor256

**Comment by yegor256** [comment]
@mbao01 are you sure we absolutely need 54 files to be modified in one pull request?

**Comment by mbao01** [comment]
@yegor256 No, not a good idea. We agreed in our last sync to make the changes smaller.

**Pull request closed without merging**
