### PR TITLE
GZip compression

### PR DESCRIPTION
**Pull request by pdacostaporto**
Solves #47.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#230](https://github.com/yegor256/0pdd/issues/230) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#230](https://github.com/yegor256/0pdd/issues/230); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@pdacostaporto did you try to use `Rack::Deflater` as we do in Zold?

**Comment by pdacostaporto** [comment]
@yegor256 I'm closing this because Github is not updating it with the new changes.

**Pull request closed without merging**
