### PR TITLE
[#333] refactor classes to be vcs independent

### PR DESCRIPTION
**Pull request by Doldrums**
[Gitlab Support] Stage 1 - Rafactoring

### CODE REVIEW

**Comment by yegor256** [comment]
@Doldrums there are merge conflict, please take a look

**Comment by yegor256** [comment]
@mbao01 ping

**Comment by Doldrums** [comment]
> @Doldrums there are merge conflict, please take a look

done

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@Doldrums did you check it locally?

**Comment by Doldrums** [comment]
> 
it was planned that you would leave your review comments, and we merge the original pr

**Comment by Doldrums** [comment]
@mbao01 or maybe you can suggest something

**Pull request closed without merging**
