### PR TITLE
[#313] allow dynamic default branch

### PR DESCRIPTION
**Pull request by mbao01**

### CODE REVIEW

**Comment by 0crat** [comment]
@mbao01[/z](https://www.0crat.com/u/mbao01) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#314` is not assigned, can't get performer

**Pull request merged**
