### PR TITLE
Updated to target Ruby 2.5.1 Updated dependencies

### LINKED ISSUE #133: deps are outdated
See https://gemnasium.com/yegor256/0pdd

Let's upgrade them. Also, can we make sure that `rake` fails if some dependencies are outdated? That would be the best solution.

### PR DESCRIPTION
**Pull request by SilasReinagel**
Fixes #133

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#186](https://github.com/yegor256/0pdd/issues/186) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job [#186](https://github.com/yegor256/0pdd/issues/186) is now out of scope

**Pull request closed without merging**
