### PR TITLE
fix #221

### LINKED ISSUE #221: Don't mention estimate if it equal to 0
Looks like #70 wasn't fully fixed because `Estimate: 0 minutes` is still there. I guess that the check that was added, tests for the `nil` value but the estimation equals to zero.

Here is the quote from original requirements:

> Let's skip the estimate if it's equal to 0 and skip the role if it's equal to IMP.

CC @yegor256 @SilasReinagel

### PR DESCRIPTION
**Pull request by lastk**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#266](https://github.com/yegor256/0pdd/issues/266) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#266](https://github.com/yegor256/0pdd/issues/266); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#266` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#266](https://github.com/yegor256/0pdd/issues/266) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Pull request merged**
