### PR TITLE
[#318] add neural net class

### PR DESCRIPTION
**Pull request by mbao01**

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@mbao01 doesn't work. Try to run `pdd -f /dev/null` locally

**Comment by mbao01** [comment]
@yegor256 thank you. Please review

**Comment by yegor256** [comment]
@rultor merge

**Comment by mbao01** [comment]
@yegor256 I am looking into what the issue is.

**Comment by mbao01** [comment]
@yegor256 please merge one last time. I fixed the issue causing the tests to fail. Thank you

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@mbao01 thanks!

**Pull request merged**
