### PR TITLE
[#311] add query param to webhook to limit isuess created

### PR DESCRIPTION
**Pull request by mbao01**
**Limit number of issues created by 0pdd.**

You can limit the number of issues created from the puzzles in your code by adding the `max_issues` key in your `.0pdd.yml` config file. `max_issues` should have a value between `1` and `99` inclusive.

### CODE REVIEW

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@mbao01 why not put this config param into `.0pdd.yml` file, like we manage other config params: https://github.com/yegor256/0pdd#how-to-configure

**Comment by mbao01** [comment]
@yegor256 we want this to be configurable by the user. The user does not have access to `.0pdd.yml` on 0pdd server.
An alternative is to find this config in `pdd`

**Comment by mbao01** [comment]
@yegor256 Yes, this works.

**Comment by mbao01** [comment]
@yegor256 thanks for pointing this out. I made the update

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
