### PR TITLE
#304 handle unorthodox process exit

### PR DESCRIPTION
**Pull request by mbao01**
Handle case where process did not exit normally.

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@mbao01 there seems to be a bug in your code

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@mbao01 sorry

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by mbao01** [comment]
@yegor256 can you merge this?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
