### PR TITLE
GZIP

### PR DESCRIPTION
**Pull request by pdacostaporto**
Solves #47

### CODE REVIEW

**Comment by pdacostaporto** [comment]
@yegor256 I don't know why @0crat didn't add this to scope

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/0pdd/issues/233#issuecomment-406811602); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by pdacostaporto** [comment]
@yegor256 this also has been some time here. Is there something left?

**Comment by yegor256** [comment]
@pdacostaporto what's up with this?

**Comment by pdacostaporto** [comment]
I just updated this to current state in master. `rake` runs without issues in my machine.

I don't know whats the problem with Rultor. It looks like it's having issues with file permissions.

Travis and AppVeyor are broken becase they're using a different version of Ruby than that in the `Gemfile`.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@pdacostaporto thanks! :)

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#233` is not assigned, can't get performer

**Pull request merged**
