### PR TITLE
[#318] linear model and pso

### PR DESCRIPTION
**Pull request by mbao01**

### CODE REVIEW

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@mbao01 I don't see a single test in this PR. How do you know it all works?

**Comment by mbao01** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@mbao01 I still don't see any tests for the classes in the `model/` directory

**Comment by mbao01** [comment]
> @mbao01 I still don't see any tests for the classes in the `model/` directory

@yegor256 There are no tests for the classes in `model/`. That is implementation details I do not wish to test. The case that I tested is _given a group of puzzles (input) into the model, does the model yield the expected rank (output)_

**Comment by mbao01** [comment]
@yegor256 did you see my comment? 👆🏾

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
