### PR TITLE
(#199) Replace body with template

### PR DESCRIPTION
**Pull request by pbenety**
Replace body with template in `github_tickets.rb` for #199

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#218](https://github.com/yegor256/0pdd/issues/218) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#218](https://github.com/yegor256/0pdd/issues/218); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@pbenety there seem to be some problems in your branch

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#218` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#218](https://github.com/yegor256/0pdd/issues/218) is now out of scope

**Pull request merged**
