### PR TITLE
Added DocType to Html Page layout.

### LINKED ISSUE #135: content-type mistake for error pages
Looks like we're setting incorrect content-type for error pages (404 and 400). That's why this is what I'm getting for http://www.0pdd.com/snapshot?name=0/_qsdssd
screen shot 2017-10-16 at 10 37 25 am

### PR DESCRIPTION
**Pull request by SilasReinagel**
Added DocType to Html Page layout. Fixes #135

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@SilasReinagel this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review; in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request merged**
