### PR TITLE
Fix and test #261

### PR DESCRIPTION
**Pull request by Serranya**
This fixes the problem described in #261

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@Serranya this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by Serranya** [comment]
Appveyor seems to be missconfigured and travis hit a rate limit
```
Error: test_configures_everything_right(TestGithub): Octokit::TooManyRequests: GET https://api.github.com/users/0pdd: 403 - API rate limit exceeded for 104.154.120.187. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
```

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@Serranya there seem to be a bug in your code. Try `rake rubocop`

**Comment by Serranya** [comment]
@yegor256 I fixed the rubocop warning.

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#262` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
