### PR TITLE
Fixed issues with tests (Windows)

### LINKED ISSUE #188: Windows Ruby 2.5.1 Test Failures
`rake` does not succeed on Windows 10 with Ruby 2.5.1 due to Test Failures. 

These two tests should be fixed.

```
========================================================================================================================D:/srcctrl/0pdd-dev/test/test_git_repo.rb:181:in `test_fetch_config'
     178:   end
     179:
     180:   def test_fetch_config
  => 181:     Dir.mktmpdir 'test' do |d|
     182:       repo = GitRepo.new(name: 'yegor256/0pdd', dir: d, uri: git(d))
     183:       repo.push
     184:       assert(repo.config['foo'])
D:/Languages/Ruby/Ruby25-x64/lib/ruby/2.5.0/tmpdir.rb:95:in `mktmpdir'
D:/Languages/Ruby/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:689:in `remove_entry'
D:/Languages/Ruby/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1386:in `postorder_traverse'
D:/Languages/Ruby/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1386:in `ensure in postorder_traverse'
D:/Languages/Ruby/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:691:in `block in remove_entry'
D:/Languages/Ruby/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1329:in `remove'
D:/Languages/Ruby/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1336:in `remove_dir1'
D:/Languages/Ruby/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1351:in `platform_support'
D:/Languages/Ruby/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1337:in `block in remove_dir1'
D:/Languages/Ruby/Ruby25-x64/lib/ruby/2.5.0/fileutils.rb:1337:in `rmdir'
Error: test_fetch_config(TestGitRepo): Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - C:/Users/SILASR~1/AppData/Local/Temp/test20180402-462444-actjr5
========================================================================================================================...........E
========================================================================================================================D:/srcctrl/0pdd-dev/test/test_job_detached.rb:37:in `test_simple_scenario'
     34:     end
     35:     JobDetached.new(
     36:       FakeRepo.new, job
  => 37:     ).proceed
     38:   end
     39: end
D:/srcctrl/0pdd-dev/objects/job_detached.rb:35:in `proceed'
D:/srcctrl/0pdd-dev/objects/job_detached.rb:52:in `exclusive'
D:/srcctrl/0pdd-dev/objects/job_detached.rb:52:in `delete'
Error: test_simple_scenario(TestJobDetached): Errno::EACCES: Permission denied @ apply2files - C:/Users/SILASR~1/AppData/Local/Temp/0pdd-lock20180402-462444-qybegw
```

### PR DESCRIPTION
**Pull request by golyalpha**
Fixed test cleanup routine in test_git_repo.rb:181-190
Fixed lock deletion in job_detached.rb:51-56

Fixes #188

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#222](https://github.com/yegor256/0pdd/issues/222) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#222](https://github.com/yegor256/0pdd/issues/222); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/0pdd#222` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#222](https://github.com/yegor256/0pdd/issues/222) is now out of scope

**Pull request merged**
